In [1]:
# importing major libraries

import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('placement.csv')

In [3]:
df.head()

   cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [4]:
df.shape

(200, 2)

In [7]:
# independent columns

x = df[['cgpa']]
x = df.iloc[:,0:-1]
x.ndim

2

In [10]:
# dependent columns
# series, not data frames

y = df['package']
y = df.iloc[:,-1]
y.ndim

1

In [29]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [30]:
x_train.head()

     cgpa
79   7.18
197  7.21
38   8.62
24   6.53
122  5.12

In [31]:
y_train.head()

79     3.00
197    3.24
38     4.36
24     2.71
122    2.01
Name: package, dtype: float64